version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trippler_db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=trippler_db